apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: devops-api
  description: DevOps API service running in Kubernetes
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition:
    $text: http://localhost:7007/api/proxy/devops-api/latest/openapi.json
