apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: devops-api
  description: DevOps API service running in Kubernetes
spec:
  type: openapi
  lifecycle: development
  owner: user:guest
  definition:
    $text: http://devops-api.devops.svc.cluster.local:8080/latest/openapi.json
